version: '3'

services:
  api:
    depends_on:
      - db
    networks:
      - um-network
    container_name: umapi
    image: "um-api"
    build:
      context: "."
      dockerfile: "UniversitiesMonitoring.Api/Dockerfile"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CONNECTION_STRING=Server=mysql;User=root;Password=denvot;Database=universities_monitoring
      - JWT_SECRET=bfbfd98b-2ccf-4f19-8025-b51c512cf2ca
      - TRUSTED_HOSTS=umapi
    restart: always
    ports:
      - "80:80"
  notify-service:
    depends_on:
      - api
    restart: always
    networks:
      - um-network
    container_name: umnotify
    image: "um-notify"
    build:
      context: "."
      dockerfile: "UniversitiesMonitoring.NotifyService/Dockerfile"
    environment:
      - DOTNET_ENVIRONMENT=Development
      - WS_URL=ws://umapi:80/api/updates-socket
      - API_URL=http://umapi:80/
      - EMAIL_ADDRESS=universitiesmonitoring@denvot.dev
      - EMAIL_PASSWORD=universitiesmonitoring
  monitoring-service:
    depends_on:
      - api
    networks:
      - um-network
    restart: always
    container_name: ummonitoring
    image: "um-mon"
    build:
      context: "."
      dockerfile: "UniversitiesMonitoring.MonitoringService/Dockerfile"
    environment:
      - DOTNET_ENVIRONMENT=Development
      - API_URL=http://umapi:80/
  db:
    networks:
      - um-network
    container_name: mysql
    image: "mysql"
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: denvot
      
networks:
  um-network:
    name: um-network